partnerbasic/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'sessions/destroy'

  get 'session/create'

  get 'sessions/new'

  resources :users do
    resources :projects do
      resources :applications do
        member do
          post 'accept_application'
          post 'reject_application'
        end
      end
      member do
        post 'create_application'
        post 'complete_project'
      end
    end
    member do
      post 'create_project'
    end
  end
  resources :reviews
  resources :company

  resources :clubs do
    resources :groups do
      member do
        post 'add_group_member'
        post 'remove_group_member'
      end
    end
    member do
      post 'add_club_member'
      post 'remove_club_member'
      post 'create_group'
      post 'make_admin'
      post 'delete_admin'
    end
  end

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

partnerbasic/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :club
  has_many :group_to_students, dependent: :destroy
  has_many :users, through: :group_to_students
  has_many :applications, dependent: :destroy
  has_many :projects

  validates :group_name, uniqueness: { scope: :club_id }
  validates :group_name, presence: true

  def add_member(user_id)
    return unless StudentToClub.exists?(user: user_id, club: club_id)
    GroupToStudent.create(group: self, user: user_id)
  end

  def remove_member(user_id)
    relationship = GroupToStudent.find_by(user: user_id, group: self)
    relationship.destroy
  end

  def full_name
    club.club_name + ': ' + group_name
  end
end

partnerbasic/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_club
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_group_member, :remove_group_member]
  helper_method :groupmember?, :admin?, :clubmember?

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group_members = @group.users
    @pending_applications = @group.applications
    @unfinished_projects = @group.projects.where(complete: false)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_group_member
    @group.add_member(current_user)
    redirect_to club_group_path(@club, @group)
  end

  def remove_group_member
    @group.remove_member(current_user)
    redirect_to club_group_path(@club, @group)
  end

  private

  def admin?
    return false unless StudentToClub.exists?(user: current_user, club: @club)
    student_to_club = StudentToClub.find_by(user: current_user, club: @club)
    student_to_club.is_admin
  end

  def groupmember?
    GroupToStudent.exists?(user: current_user, group: @group)
  end

  def clubmember?
    StudentToClub.exists?(user: current_user, club: @club)
  end

  def set_club
    @club = Club.find(params[:club_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:club_id, :group_name)
  end
end

partnerbasic/app/helpers/groups_helper.rb
module GroupsHelper
end

partnerbasic/app/views/groups/_form.html.erb
<%= form_with model: [@club, @group] do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :club_id %>
    <%= form.text_field :club_id, id: :group_club_id %>
  </div>

  <div class="field">
    <%= form.label :group_name %>
    <%= form.text_field :group_name, id: :group_group_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

partnerbasic/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

partnerbasic/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Club</th>
      <th>Group name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.club %></td>
        <td><%= group.group_name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_club_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_club_group_path %>

partnerbasic/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', club_groups_path %>

partnerbasic/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>

<div class="container">
    <% if !@group_members.empty? %>
      <h3> Group Members </h3>
    <% end %>
    <% @group_members.each do |member| %>
      <tr>
        <%= link_to "#{member.name}", member, class: 'btn-link btn'%>
        <br>
      </tr>
    <% end %>
</div>

<div class="container">
    <% if !groupmember? && student? && clubmember? %>
    <%= link_to 'Join Group', add_group_member_club_group_path(group_id: @group), method: :post, class: 'btn-link btn' %>
    <% end %>

    <% if groupmember? && student? %>
    <%= link_to 'Leave Group', remove_group_member_club_group_path(group_id: @group), method: :post, class: 'btn-link btn' %>
    <% end %>
</div>
<% if groupmember? && student? %>
  <div class="container">
      <% if !@unfinished_projects.empty? %>
        <h3> Projects under way </h3>
      <% end %>
      <% @unfinished_projects.each do |unfinished_project| %>
          <div class="row container">
            <%= "#{unfinished_project.user.name}'s #{unfinished_project.project_name} " %>
            <br>
          </div>
      <% end %>
   </div>
    <div class="container">
      <% if !@pending_applications.empty? %>
        <h3> Pending Applications </h3>
      <% end %>
      <% @pending_applications.each do |pending_application| %>
          <div class="row container">
            <%= "#{pending_application.project.user.name}'s #{pending_application.project.project_name} " %>
            <%= link_to "Delete", user_project_application_path(pending_application.project.user, pending_application.project, pending_application), method: :delete, data: { confirm: 'Are you sure?' } %>
          <br>
          </div>
      <% end %>
    </div>
<% end %>
<% if admin? %>
<%= link_to 'Edit', edit_club_group_path(@club), class: 'btn-info btn', :style => 'color: white' %>
<% end %>
<%= link_to 'Back', @club, class: 'btn-warning btn', :style => 'color: white' %>