partnerbasic/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'sessions/destroy'

  get 'session/create'

  get 'sessions/new'

  resources :users do
    resources :projects do
      resources :applications do
        member do
          post 'accept_application'
          post 'reject_application'
        end
      end
      member do
        post 'create_application'
        post 'complete_project'
      end
    end
    member do
      post 'create_project'
    end
  end
  resources :reviews
  resources :company

  resources :clubs do
    resources :groups do
      member do
        post 'add_group_member'
        post 'remove_group_member'
      end
    end
    member do
      post 'add_club_member'
      post 'remove_club_member'
      post 'create_group'
      post 'make_admin'
      post 'delete_admin'
    end
  end

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

partnerbasic/app/models/application.rb
class Application < ApplicationRecord
  belongs_to :group
  belongs_to :project

  validates :group_id, uniqueness: { scope: :project_id }
end

partnerbasic/app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :student?, :current_user

  def logged_in?
    if !User.exists?(id: session[:user_id])
      false
    else
      session[:user_id]
    end
  end

  def student?
    session[:user_type]
  end

  def current_user
    if !User.exists?(id: session[:user_id])
      reset_session
    elsif logged_in?
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authenticate_user
    redirect_to root_path unless logged_in?
  end

  def change_admin_status(user, club, status)
    return unless StudentToClub.exists?(user: user, club: club)
    student_to_club = StudentToClub.find_by(user: user, club: club)
    student_to_club.update_attributes(is_admin: status)
    redirect_to club
  end

  def check_admin_status(user, club)
    return false unless StudentToClub.exists?(user: user, club: club)
    student_to_club = StudentToClub.find_by(user: user, club: club)
    student_to_club.is_admin
  end

  def remove_current_user(user, club)
    club.remove_member(user)
    redirect_to club
  end
end

partnerbasic/app/controllers/applications_controller.rb
# Applications Controller
class ApplicationsController < ApplicationController
  before_action :set_user
  before_action :set_project
  before_action :set_application, only: %i[show edit update destroy
                                           accept_application
                                           reject_application]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show; end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit; end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html do
        redirect_to root_path,
                    notice: 'Application was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def accept_application
    @project.update_attributes(group: @application.group)
    @application.destroy
    redirect_to user_project_path(@user, @project)
  end

  def reject_application
    @application.destroy
    redirect_to user_project_path(@user, @project)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:project_id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def application_params
    params.require(:application).permit(:text,
                                        :date_added, :group_id, :project_id)
  end
end

partnerbasic/app/helpers/application_helper.rb
module ApplicationHelper
end

partnerbasic/app/helpers/applications_helper.rb
module ApplicationsHelper
end

partnerbasic/app/views/applications/_form.html.erb
<%= form_with(model: application, local: true) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :application_text %>
  </div>

  <div class="field">
    <%= form.label :date_added %>
    <%= form.datetime_select :date_added, id: :application_date_added %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id, id: :application_group_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :application_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

partnerbasic/app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

partnerbasic/app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Date added</th>
      <th>Group</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.text %></td>
        <td><%= application.date_added %></td>
        <td><%= application.group %></td>
        <td><%= application.project %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

partnerbasic/app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

partnerbasic/app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @application.text %>
</p>

<p>
  <strong>Date added:</strong>
  <%= @application.date_added %>
</p>

<p>
  <strong>Group:</strong>
  <%= @application.group %>
</p>

<p>
  <strong>Project:</strong>
  <%= @application.project %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>