partnerbasic/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'sessions/destroy'

  get 'session/create'

  get 'sessions/new'

  resources :users do
    resources :projects do
      resources :applications do
        member do
          post 'accept_application'
          post 'reject_application'
        end
      end
      member do
        post 'create_application'
        post 'complete_project'
      end
    end
    member do
      post 'create_project'
    end
  end
  resources :reviews
  resources :company

  resources :clubs do
    resources :groups do
      member do
        post 'add_group_member'
        post 'remove_group_member'
      end
    end
    member do
      post 'add_club_member'
      post 'remove_club_member'
      post 'create_group'
      post 'make_admin'
      post 'delete_admin'
    end
  end

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

partnerbasic/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :group, required: false
  has_many :applications, dependent: :destroy

  validates :project_name, uniqueness: { scope: :user_id }
  validates :project_name, presence: true
end

partnerbasic/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user
  before_action :set_project, only: [:show, :edit, :update, :destroy, :create_application, :complete_project]
  helper_method :company?, :owner?, :taken?

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @user_groups = current_user.nil? ? [] : current_user.groups
    @project_applications = @project.applications
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to user_project_path(@user, @project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: user_project_path(@user, @project) }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_application
    unless params['selected_group'].empty?
      @application = Application.new(text: params['application_text'], group: Group.find(params['selected_group']), project: @project)
      @application.save
    end
    redirect_to user_project_path(@user, @project)
  end

  def complete_project
    @review = Review.new(review_text: params['review_text'], club: @project.group.club, user: @user)
    @review.save
    @project.update_attributes(complete: true)
    redirect_to @user
  end

  private

  def company?
    !@user.is_student
  end

  def owner?
    @user == current_user
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def taken?
    !@project.group_id.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:user_id, :project_name, :description, :group_id)
  end
end

partnerbasic/app/helpers/projects_helper.rb
module ProjectsHelper
end

partnerbasic/app/views/projects/_form.html.erb
<%= form_with model: [@user, @project] do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, id: :project_project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

partnerbasic/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', user_project_path(@user, @project) %>

partnerbasic/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project name</th>
      <th>Description</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.user %></td>
        <td><%= project.project_name %></td>
        <td><%= project.description %></td>
        <td><%= project.group %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

partnerbasic/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

partnerbasic/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Group:</strong>
  <% if !taken? %>
    None, be part of a group and apply now!
  <% else %>
    <%= @project.group.full_name %>
  <% end %>
</p>

<br>

<% if !taken? %>
    <% if student? && @user_groups.any? %>
      <%= form_with(url: create_application_user_project_path, local:true) do |form|%>
        <div class="field">
          <%= form.text_area :application_text, :cols => "80", :rows => "20", placeholder: 'Write your application here!' %>
        </div>
        <div class="field">
          <%= form.collection_select(:selected_group, @user_groups, :id, :full_name, prompt: 'Select your group') %>
        </div>
        <div class="actions">
          <%= form.submit 'Apply', disabled: false, class: 'btn-success btn', :style => 'color: white'%>
        </div>
      <% end %>
    <% end %>

    <% if company? && owner? %>
        <% @project_applications.each do |application| %>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= application.group.full_name %></h5>
              <br>
              <%= application.created_at %>
              <br>
              <p class="card-text"><%= application.text %></p>
              <br>
              <%= link_to 'Show', club_path(application.group.club), class: 'btn-info btn', :style => 'color: white' %>
              <%= link_to 'Accept', accept_application_user_project_application_path(@user, @project, application), method: :post, class: 'btn-success btn', :style => 'color: white' %>
              <%= link_to 'Reject', reject_application_user_project_application_path(@user, @project, application), method: :post, class: 'btn-danger btn', :style => 'color: white' %>
            </div>
          </div>
        <% end %>
    <% end %>
<% else %>
    <% if company? && owner? && (@project.complete.nil? || !@project.complete) %>
      <%= form_with(url: complete_project_user_project_path, local:true) do |form|%>
        <div class="field">
          <%= form.text_area :review_text, :cols => "80", :rows => "20",  placeholder: 'Write your review here once the project is done!'%>
        </div>
        <div class="actions">
          <%= form.submit 'Mark as Complete', disabled: false, class: 'btn-success btn', :style => 'color: white'%>
        </div>
      <% end %>
    <% end %>
<% end %>
<br>
<% if owner? %>
  <%= link_to 'Edit', edit_user_project_path(@user, @project), class: 'btn-info btn', :style => 'color: white' %>
<% end %>
<%= link_to 'Back', @user, class: 'btn-warning btn', :style => 'color: white' %>