partnerbasic/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'sessions/destroy'

  get 'session/create'

  get 'sessions/new'

  resources :users do
    resources :projects do
      resources :applications do
        member do
          post 'accept_application'
          post 'reject_application'
        end
      end
      member do
        post 'create_application'
        post 'complete_project'
      end
    end
    member do
      post 'create_project'
    end
  end
  resources :reviews
  resources :company

  resources :clubs do
    resources :groups do
      member do
        post 'add_group_member'
        post 'remove_group_member'
      end
    end
    member do
      post 'add_club_member'
      post 'remove_club_member'
      post 'create_group'
      post 'make_admin'
      post 'delete_admin'
    end
  end

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

partnerbasic/app/models/club.rb
class Club < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :student_to_clubs, dependent: :destroy
  has_many :users, through: :student_to_clubs
  has_many :groups, dependent: :destroy

  validates :club_name, uniqueness: { scope: :university_name }, allow_blank: false, presence: true

  def add_member(user_id, is_admin)
    StudentToClub.create(club: self, user: user_id, is_admin: is_admin)
  end

  def remove_member(user_id)
    relationship = StudentToClub.find_by(user: user_id, club: self)
    relationship.destroy
    groups.each { |group| GroupToStudent.where(user: user_id, group: group).destroy_all }
  end
end

partnerbasic/app/controllers/clubs_controller.rb
# Controller for clubs
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy, :add_club_member, :remove_current_user, :remove_club_member, :create_group, :make_admin, :delete_admin]
  helper_method :admin?, :adminv2?, :member?, :only_admin?

  def index
    @clubs = Club.all
  end

  def show; end

  def new
    @club = Club.new
  end

  def edit; end

  def create
    @club = Club.new(club_params)
    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        form_with_error(format, @club.errors)
      end
    end
    @club.add_member(current_user, true)
  end

  def form_with_error(format, errors)
    format.html { render :new }
    format.json { render json: errors, status: :unprocessable_entity }
  end

  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @club.destroy
    redirect_to clubs_url
  end

  def add_club_member
    @club.add_member(current_user, false)
    redirect_to @club
  end

  def remove_club_member
    if only_admin? && admin?
      if applications? || projects?
        format_redirect_helper('Club still has pending or unfinished applications', @club)
      else
        @club.destroy
        format_redirect_helper('Club was successfully destroyed.', clubs_url)
      end
    else
      remove_current_user(current_user, @club)
    end
  end

  def format_redirect_helper(notice, redirect_target)
    respond_to do |format|
      format.html { redirect_to redirect_target, notice: notice }
      format.json { head :no_content }
    end
  end

  def create_group
    @group = Group.new(club: @club, group_name: params['group_name'])
    @group.save
    redirect_to @club
  end

  def make_admin
    change_admin_status(params['member'], @club, true)
  end

  def delete_admin
    change_admin_status(params['member'], @club, false)
  end

  private

  def projects?
    @club.groups.any? { |group| Project.exists?(group: group, complete: false) }
  end

  def applications?
    @club.groups.any? { |group| Application.exists?(group: group) }
  end

  def only_admin?
    StudentToClub.select { |m| m.is_admin && m.club == @club }.size == 1 && admin?
  end

  def admin?
    check_admin_status(current_user, @club)
  end

  def adminv2?(user)
    check_admin_status(user, @club)
  end

  def member?
    StudentToClub.exists?(user: current_user, club: @club)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_club
    @club = Club.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def club_params
    params.require(:club).permit(:club_name, :university_name, :club_link, :description, :photo_link, :verified)
  end
end

partnerbasic/app/helpers/clubs_helper.rb
module ClubsHelper
end

partnerbasic/app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :club_name %>
    <%= form.text_field :club_name, id: :club_club_name %>
  </div>

  <div class="field">
    <%= form.label :university_name %>
    <%= form.text_field :university_name, id: :club_university_name %>
  </div>

  <div class="field">
    <%= form.label :club_link %>
    <%= form.text_field :club_link, id: :club_club_link %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :club_description %>
  </div>

  <div class="field">
    <%= form.label :photo_link %>
    <%= form.text_field :photo_link, id: :club_photo_link %>
  </div>

  <div class="field">
    <%= form.label :verified %>
    <%= form.check_box :verified, id: :club_verified %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

partnerbasic/app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

partnerbasic/app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Clubs</h1>
<% @clubs.each do |club| %>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"> <%= club.club_name %> </h5>
    <% if !club.university_name.empty? %>
      <%= club.university_name %>
    <% end %>
    <% if !club.photo_link.empty? %>
      <%= image_tag("#{club.photo_link}", :style => 'width: 50px; height: 50px; display: block; margin: auto') %>
    <% end %>
    <p class="card-text"><%= club.description %></p>
    <%= link_to 'Show', club, class: 'btn-info btn', :style => 'color: white' %>
  </div>
</div>
<% end %>

<br>
<% if logged_in? && student? %>
<%= link_to 'Add Your Club!', new_club_path, class: 'btn-success btn', :style => 'color: white' %>
<% end %>

partnerbasic/app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', clubs_path %>

partnerbasic/app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
<div class="container">
    <h1 class="display-3"><%= @club.club_name %></h1>
    <% if !@club.university_name.empty? %>
      <%= @club.university_name %>
    <% end %>
    <p><%= @club.description %></p>
  <% if admin? %>
    <%= link_to 'Edit', edit_club_path(@club), class: 'btn-info btn', :style => 'color: white' %>
  <% end %>
  </div>
</div>

<div class="row container">
  <% if !member? && student? %>
  <%= link_to 'Join Club', add_club_member_club_path, method: :post, class: 'btn-info btn', :style => 'color: white' %>
  <% end %>

  <% if member? && student? %>
  <%= link_to 'Leave Club', remove_club_member_club_path, method: :post, data: { confirm: 'If you are the last admin, leaving will delete the club!' }, class: 'btn-warning btn', :style => 'color: white' %>
  <% end %>
  <%= link_to 'Back', clubs_path,  class: 'btn-info btn', :style => 'color: white' %>
</div>
<% if !@club.users.empty? %>
  <h2> Members </h2>
<% end %>
<% @club.users.each do |member| %>
  <tr>
    <% if adminv2?(member) %>
      &#9813;
    <% end %>
    <td><%= link_to "#{member.name}".html_safe, member, class: 'btn-link btn'%></td>
    <% if admin? %>
      <% if !adminv2?(member) %>
        <%= link_to "Make Admin", make_admin_club_path(@club, :member => member), method: :post %>
      <% else %>
        <% if !only_admin? %>
          <%= link_to "Delete Admin", delete_admin_club_path(@club, :member => member), method: :post %>
        <% end %>
      <% end %>
    <% end %>
    <br>
  </tr>
<% end %>

<br>

<% if !@club.groups.empty? %>
  <h2> Groups </h2>
<% end %>
<% @club.groups.each do |group| %>
  <tr>
    <td><%= link_to "#{group.group_name}", club_group_path(@club, group), class: 'btn-link btn' %></td>
    <br>
  </tr>
<% end %>

<br>

<% if admin? %>
  <%= form_with(url: create_group_club_path, local:true) do |form|%>
    <div class="field">
      <%= form.label :group_name%>
      <%= form.text_field :group_name%>
    </div>
    <div class="actions">
      <%= form.submit 'Create', disabled: false%>
    </div>
  <%end%>
<% end %>

<% @club.reviews.each do |review| %>
  <div class="card">
    <div class="card-body">
      <% if review.user.nil? %>
        <h5 class="card-title"> Employer deleted </h5>
      <% else %>
        <h5 class="card-title"> <%= review.user.name %> </h5>
      <% end %>
      <p class="card-text"><%= review.review_text %></p>
    </div>
  </div>
<% end %>